### ISSUE TITLE
Mkvmerge Error

### ISSUE THREAD

**Issue by Gamina67** [dropcreations/MKVToolNix-in-Google-Colab#5]
@dropcreations Hi.
I was trying merge VOB files from DVD to MKV using mkvmerge everything going right no error or anything, btw i left everything blank except for output path. But the problem is only audio getting merged not the Video(i mean it's only audio in mkv format) btw i did not put all the VOB files one by one in `inputfile:` rather put the first one(VTS_02_1.VOB) and following files processed by itself just like in the gui, idk what I'm doing wrong so can you pls try and tell me. anyway here's the output result
inputFile: /content/drive/Shareddrives/Dummy/Whitesnake - Restless Heart (DVD)/VIDEO_TS/VTS_02_1.VOB

ID  Type   Lang   Codec
--  ----   ----   -----
0  video   None   MPEG-1/2
1  audio   None   PCM

track ID: 1
|
|--trackTitle: 
|--trackLanguage: 
|--Set track as default? [y/n] 
|--Set track as forced? [y/n] 

inputFile: Done

outputFilename: Whitesnake
mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
'/content/drive/Shareddrives/Dummy/Whitesnake - Restless Heart (DVD)/VIDEO_TS/VTS_02_1.VOB': Using the demultiplexer for the format 'MPEG program stream'.
'/content/drive/Shareddrives/Dummy/Whitesnake - Restless Heart (DVD)/VIDEO_TS/VTS_02_1.VOB': Processing the following files as well: "VTS_02_2.VOB", "VTS_02_3.VOB", "VTS_02_4.VOB"
'/content/drive/Shareddrives/Dummy/Whitesnake - Restless Heart (DVD)/VIDEO_TS/VTS_02_1.VOB' track 1: Using the output module for the format 'PCM'.
The file '/content/drive/Shareddrives/Dummy/Whitesnake - Restless Heart (DVD)/Whitesnake.mkv' has been opened for writing.
Progress: 100%
The cue entries (the index) are being written...
Multiplexing took 37 seconds.

**Comment by dropcreations** [comment]
@Gamina67 Hi..

For a example get the file **VTS_02_1.VOB**

To merge this file into **.mkv** you have to insert the file twice at `inputFile:`. First time for the video (`track ID: 0`) and second time for the audio (`track ID: 1`). In the output you attached above, you have only added the audio track that's why the final output was only a audio.

Thanks for using this project..!

**Comment by Gamina67** [comment]
@dropcreations yes that was it thanks for pointing out.
But i have this subtitle problem now, cell not recognizing subtitles only video & audio file like this :
ID              Type         Lang
0               Video       None
1               Audio       None
2               Audio       None
3               Audio       None
Here's the media info of file I'm trying to mux https://pastebin.com/raw/8JNNu0mz

**Comment by dropcreations** [comment]
@Gamina67 **Give me the source file link.**
I think mkvmerge doesn't support that subtitle format

**Comment by Gamina67** [comment]
> @Gamina67 **Give me the source file link.** I think mkvmerge doesn't support that subtitle format

Hi... sorry for the late reply
If it doesn't support there's nothing u can do ig anyway thanks for clearing this up 👍. Also how about makemkv does that make any difference than mkvtoolnix just a thought.
Keep up the Good work mate.
